### ISSUE TITLE
[FEATURE]  Want to add our Contributor page in the website

### ISSUE THREAD

**Issue by HimanshuNarware** [aniketsinha2002/DataScienceWebsite.github.io#727] opened 2023-08-07 11:01 UTC
### Description

Details
Is your feature request related to a problem? Please describe.
Our Contributors page in the website
Describe the solution you'd like
We can add a Contributors page in the website. which is shows the name and the profile image of the contributor.and the number of commits is done by the contributor

**Comment by Sriya003** [comment] 2023-09-07 17:28
I want to do it

**Comment by aniketsinha2002** [comment] 2023-09-07 19:25
Hey @Sriya003 the issue is already fixed! Go through the website and try to find a bug or something which you want to improve. Create an issue regarding that and I'll assign it to you !!

**Closed by aniketsinha2002** 2023-09-07 19:25 UTC
Labels: Already Fixed
